using System;
using Postgrest.Attributes;
using Supabase;

namespace BlazorWebAssemblySupabaseTemplate.Dtos;

[Table("Lista")]
public class Lista : SupabaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public int Id { get; set; }

    [Column("titulo")]
    public string titulo { get; set; }

    [Column("apagado")]
    public bool apagado { get; set; }

    [Column("data_criacao")]
    public DateTime data_criacao { get; set; }

    [Column("data_modificacao")]
    public DateTime data_modificacao { get; set; }
    
    [Column("user_id")]
    public string user_id { get; set; }
}
