using System;
using Postgrest.Attributes;
using Postgrest.Models;
using Supabase;

namespace BlazorWebAssemblySupabaseTemplate.Dtos;

[Table("Todo")]
public class Todo : BaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public int Id { get; set; }

    [Column("Title")]
    public string? Title { get; set; }

    [Column("SoftDelete")]
    public bool? SoftDelete { get; set; }  // type bool don't work. Throw Unhandled exception rendering component: Key should reference a Model Property.
    // public string? SoftDelete { get; set; }  // type string works fine
    
    [Column("SoftDeletedAt")]
    public DateTime? SoftDeletedAt { get; set; }

}
